version: 2
 
sources:
  - name: coffee_shop
    project: analytics-engineers-club
    description: database of coffee shop data
    tables:
      - name: products
      - name: order_items

      - name: product_prices
        description: price of product
        columns: 
          - name: price
            tests:
              - greater_than_null

      - name: customers
        description: table with customer information
        columns: 
          - name: id
            tests:
              - unique
              - not_null
      
      - name: orders
        description: table with order information
        columns: 
          - name: id
            tests: 
              - unique
              - not_null
